apiVersion: v1
kind: Service
metadata:
  name: '{{.Values.microservices.CartService.serviceName}}'
spec:
  selector:
    app: '{{.Values.microservices.CartService.serviceName}}'
  ports:
  - name: http
    port: 80
    targetPort: 1
  type: ClusterIP
